version = 0.1
[default.deploy.parameters]
stack_name = "test"
resolve_s3 = true
s3_prefix = "test"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "EventBusName=\"OrderEventBus\" DynamoDBTableName=\"Orders\" SQSQueueName=\"OrderQueue\" SNSTopicName=\"OrderNotifications\""
image_repositories = []
