AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless Event-Driven Order Processing System

Parameters:
  Environment:
    Type: String
    Description: Environment (e.g., dev, staging, prod)

Resources:
  # API Gateway
  OrderSubmissionApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Environment
      Description: Order Submission API
      EndpointConfiguration: REGIONAL
      Cors:
        AllowMethods: "'POST'"
        AllowHeaders: "'Content-Type'"
        AllowOrigin: "'*'"

  # Order Submission Lambda
  OrderSubmissionFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/order_validation.lambda_handler
      Runtime: python3.9
      CodeUri: .
      Environment:
        Variables:
          EVENT_BUS_NAME: !Ref OrderProcessingEventBus
      Events:
        SubmitOrder:
          Type: Api
          Properties:
            Path: /order
            Method: POST
            RestApiId: !Ref OrderSubmissionApi

  # EventBridge Event Bus
  OrderProcessingEventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: OrderProcessingEventBus

  # SQS Queue for Valid Orders
  OrderQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: OrderQueue.fifo
      FifoQueue: true
      ContentBasedDeduplication: true

  # Dead-Letter Queue for Invalid Orders
  DLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: DeadLetterQueue.fifo
      FifoQueue: true
      ContentBasedDeduplication: true

  # Order Validation Lambda
  OrderValidationFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/order_validation.lambda_handler
      Runtime: python3.9
      CodeUri: .
      Policies:
        - SQSReadPolicy:
            QueueName: !Ref OrderQueue
      Environment:
        Variables:
          SQS_QUEUE_URL: !GetAtt OrderQueue.QueueUrl
          DLQ_URL: !GetAtt DLQ.QueueUrl

  # Inventory Management Lambda
  InventoryCheckFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/inventory_check.lambda_handler
      Runtime: python3.9
      CodeUri: .
      Policies:
        - DynamoDBCrudPolicy:
            TableName: OrderTable
      Events:
        OrderQueueTrigger:
          Type: SQS
          Properties:
            Queue: !GetAtt OrderQueue.Arn

  # DynamoDB Table
  OrderTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Orders
      AttributeDefinitions:
        - AttributeName: orderId
          AttributeType: S
      KeySchema:
        - AttributeName: orderId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  # Order Completion Lambda
  OrderCompletionFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/order_completion.lambda_handler
      Runtime: python3.9
      CodeUri: .
      Policies:
        - DynamoDBCrudPolicy:
            TableName: OrderTable
      Environment:
        Variables:
          EVENT_BUS_NAME: !Ref OrderProcessingEventBus

  # Notification Lambda
  NotificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/notification.lambda_handler
      Runtime: python3.9
      CodeUri: .
      Policies:
        - SNSPublishMessagePolicy:
            Topics: !Ref NotificationTopic
      Environment:
        Variables:
          NOTIFICATION_TOPIC: !Ref NotificationTopic

  # SNS Topic for Notifications
  NotificationTopic:
    Type: AWS::SNS::Topic

Outputs:
  ApiEndpoint:
    Description: API Gateway Endpoint
    Value: !Sub "https://${OrderSubmissionApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/order"
    Export:
      Name: ApiEndpoint
