name: Deploy SAM Application
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install AWS SAM CLI
        run: |
          pip install aws-sam-cli

      - name: Create virtual environment and install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
        shell: bash

      - name: Build SAM application
        run: |
          source .venv/bin/activate
          sam build
        shell: bash

      - name: Check Stack Status
        run: |
          STACK_STATUS=$(aws cloudformation describe-stacks --stack-name order-processing-system --query 'Stacks[0].StackStatus' --output text)
          if [[ "$STACK_STATUS" == "UPDATE_FAILED" ]]; then
            echo "Rolling back stack..."
            aws cloudformation rollback-stack --stack-name order-processing-system
          fi
      - name: Deploy SAM Stack
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: |
          source .venv/bin/activate
          sam deploy \
          --no-confirm-changeset \
          --stack-name order-processing-system \
          --region $AWS_REGION \
          --capabilities CAPABILITY_IAM \
          --resolve-s3 \
          --parameter-overrides Environment=prod
        shell: bash