name: Deploy to AWS
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy SAM Stack
        run: |
            sam deploy \
            --stack-name order-processing-system \
            --region us-east-1 \
            --capabilities CAPABILITY_IAM \
            --parameter-overrides \
            EventBusName=${{ secrets.EVENT_BUS_NAME }} \
            DynamoDBTableName=${{ secrets.DYNAMODB_TABLE_NAME }} \
            SQSQueueName=${{ secrets.SQS_QUEUE_NAME }} \
            SNSTopicName=${{ secrets.SNS_TOPIC_NAME }}
